[package]
name = "ansible"
version = "0.1.0"
authors = ["agf46 <akshaygf@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-chain = "0.12.4"
regex = "1.4.3"