[package]
name = "dockerd_logs"
version = "0.1.0"
authors = ["agf46 <akshaygf@gmail.com>"]
description = "Search for dockerd errors faster"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
